# Generated by Django 5.0 on 2024-01-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='pic-1.jpg', upload_to='media/upload'),
        ),
    ]
