# Generated by Django 5.0 on 2024-01-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_chairman_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('contect', models.CharField(max_length=11)),
                ('blockno', models.CharField(max_length=3)),
                ('houseno', models.CharField(max_length=4)),
                ('occupation', models.CharField(max_length=50)),
                ('job_address', models.TextField()),
                ('bloodgroup', models.CharField(max_length=3)),
                ('vehical_details', models.CharField(max_length=20)),
                ('pic', models.FileField(default='pic-1.jpg', upload_to='media/upload')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
